---
title: '2018-10-03'
output: html_document
---



```{r}
library(stringr)
```


```{r}
str_c(letters,LETTERS)
str_c(letters,LETTERS,sep="-")
str_c("lowercase: ", letters, ", capital: ", LETTERS)
```



```{r}
str_split_fixed()
```

```{r}
fruits <- c(
  "apples and oranges and pears and bananas",
  "pineapples and mangos and guavas"
)
str_split_fixed(fruits, " and ", 3)
str_split_fixed(fruits, " and ", 4)

```


```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
```

```{r}
library(googlesheets)
gs_auth(new_user = TRUE)

```


```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```


```{r}
library(lubridate)
library(stringr)
library(googlesheets)

```

```{r}
gs_auth(new_user = TRUE)
```


```{r}
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```

```{r}
class(classSurvey)
```
```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
as.character(StuDF$name) -> StuDF$name

```

```{r}
StuDF <- data.frame(
  StuID=c(1,2,3,4,5),
  name=c("小明","大雄","胖虎","小新","大白"),
  score=c(80,60,90,70,50),
  stringsAsFactors = F
  )
StuDF 
```
```{r}
names(StuDF) 
colnames(StuDF)
```

```{r}
rownames(StuDF)
```

```{r}
(StuDF$score >= 80)
(StuDF$name=="小新")
```

```{r}
StuDF[c(1,4),]
StuDF[-c(1,4),]
```

```{r}
StuDF[1,2]
#StuDF[,2]
#StuDF[1,]
#StuDF[c(1,4),]
#StuDF[c(1,4),c(2,3)]
```
```{r}
StuDF[c(T,F,F,F,F),c(F,T,F)]
StuDF[c(T,F,F,T,F),]
```
```{r}
a<-c(T,T,F,F,T,F,F)
sum(a)
```

```{r}
(StuDF$score >= 80)
(StuDF$name == "小新")
StuDF[which(StuDF$score>=80),2]
StuDF[c(1,3),2]
StuDF[(StuDF$score>=80),2]
StuDF[c(T,F,T,F,F),2]
StuDF[which(StuDF$name == "小新"),3]
```

```{r}
aa<-(classSurvey$性別 == "男")

bb<-(classSurvey$本學期學分數 > 20)

cc<-(classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 20)
cbind(aa,bb,cc)
```

```{r}
library(stringr)
(classSurvey$性別 == "男" | 
    classSurvey$本學期學分數 > 26)
#classSurvey[which(classSurvey$性別=='男') | classSurvey$本學期學分數>26,3]
#as. stringr::str_split(classSurvey$居住地行政區 == 台北市)
```
```{r}
aaa<-c(3,7,9,10)
aaa[3]
```

```{r}
StuDF$StuID
StuDF[,c("StuID")]
StuDF$name
StuDF[,c("name")]
```
```{r}
StuDF[,c("StuID","name")]

## 無法用$一次取兩個元素
# StuDF$c("StuID","name")
```

```{r}
StuDF[c(1,4),c(2)]
StuDF[,c(2)][c(1,4)]

## the second one is equivalent to 
StuDF[,c(2)] -> aa
aa[c(1,4)] 
```

```{r}
StuDF[,c(1,3)][c(1,4),]

```

```{r}
names(StuDF)
```

```{r}
names(StuDF) <- c("學號","姓名","成績")
names(StuDF)
```

```{r}
library(readr)
student <- read_csv("https://raw.githubusercontent.com/tpemartin/course-107-1-programming-for-data-science/master/data/student.csv")
library(dplyr)
library(magrittr)
student %<>% mutate(
  身高級距=cut(身高,c(0,150,155,160,165,170,175,180,185,200)))
```

```{r}
StuDF$成績[c(4)]
StuDF$成績[c(4)] <- 75
```

```{r}
student$新身高級距 <- student$身高級距
```

```{r}
levels(student$身高級距)[c(1:3)]<-"(0,160]"
levels(student$身高級距)
```
```{r}
dim(classSurvey)
```

```{r}
as.factor(student) <-student$年級
levels()
```


```{r}
library(googlesheets)
#gs_auth(new_user = TRUE)
gsSurvey<-gs_key("1mC9bnxj11NCNoOCw0Vmn4nxERbHtLjeGo9v9C9b2GDE")  #download sheet information as an object
classSurvey<-gs_read(gsSurvey,ws=1) #access the 1st worksheet
```
```{r}
dim(classSurvey)
nrow(classSurvey)
ncol(classSurvey)
```

```{r}
class(classSurvey$學號)
# 學號轉成character
# 學號取出字串第2-4位 存成 年級
# 年級 轉 factor
# 年級進行 generic replacement
```
```{r}
class(classSurvey$學號)
# 學號轉成character
classSurvey$學號 <- as.character(classSurvey$學號)
# 學號取出字串第2-4位 存成 年級
library(stringr)
classSurvey$年級 <- str_sub(classSurvey$學號,2,4)
# 年級 轉 factor
classSurvey$年級 <- as.factor(classSurvey$年級)
# 年級進行 generic replacement
levels(classSurvey$年級) <- c("大四及以上","大三","大二","大一")
```

```{r}
freshActivity<-
  classSurvey$本學期目前已參加之課外活動[(classSurvey$年級=="大一")]
library(stringr)
str_split_fixed(freshActivity,",",n=5)->aa
str_c(aa)->bb
```

#20181107
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
民國年月<-c("099/01","099/02","099/03")
```

```{r}
library(stringr)
library(lubridate)
民國年月<-c("099/01","099/02","099/03")
# 1
str_c("1",民國年月,"/01")->民國年月
# 2
lubridate::ymd(民國年月) -> 民國年月
# 3
民國年月 + years(911)
```

```{r}
民國年月<-c("099/01","099/02","099/03")
library(dplyr)
# 1
民國年月 %>% 
  str_c("1", . ,"/01") %>%
  ymd %>%
  { . + years(911) }
```


```{r}
library(readr)
collegeData <- read_csv("https://quality.data.gov.tw/dq_download_csv.php?nid=6231&md5_url=dda8fca407131483c1d8cbf3d61cf793")
```

```{r}
collegeData$學校名稱 <-
  as.factor(collegeData$學校名稱)
collegeData$`日間∕進修別`<-
  as.factor(collegeData$`日間∕進修別`)
```

```{r}
library(dplyr)
mutate(
  collegeData,
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
  ) -> collegeData2
```

```{r}
collegeData %>%
  mutate(.,
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
         ) -> collegeData2
```

```{r}
collegeData %>%
  mutate(
  學校代碼=as.factor(學校代碼),
  學校名稱=as.factor(學校名稱)
         ) -> collegeData2
```
# 舊寫法

```{r}
collegeData$學校代碼<-as.factor(collegeData$學校代碼)
collegeData$學校名稱<-as.factor(collegeData$學校名稱)
collegeData -> collegeData2
```

```{r}
collegeData$`日間∕進修別`<-as.factor(collegeData$`日間∕進修別`)
collegeData$等級別<-as.factor(collegeData$等級別)

collegeData$一年級男生<-as.numeric(collegeData$一年級男生)
collegeData$一年級女生<-as.numeric(collegeData$一年級女生)

collegeData -> collegeData2
```

# mutate寫法

```{r}
library(dplyr)
mutate(collegeData,
       `日間∕進修別`=as.factor(`日間∕進修別`),
       等級別=as.factor(等級別),
       一年級男生=as.numeric(一年級男生),
       一年級女生=as.numeric(一年級女生)
       ) ->
  collegeData2
```

# pipe


```{r}
library(dplyr)
collegeData %>%
mutate(
       `日間∕進修別`=as.factor(`日間∕進修別`),
       等級別=as.factor(等級別),
       一年級男生=as.numeric(一年級男生),
       一年級女生=as.numeric(一年級女生)
       ) ->
  collegeData2
```

# pipe


```{r}
library(dplyr)
collegeData %>%
  mutate( #將所有逗號拿掉
       `日間∕進修別`=as.factor(`日間∕進修別`),
       等級別=as.factor(等級別),
       一年級男生=as.numeric(一年級男生),
       一年級女生=as.numeric(一年級女生)
       ) ->
  collegeData2
```

```{r}
library(stringr)
collegeData %>%
  mutate( #將字串轉成數值
    一年級男生=str_replace(一年級男生,",",""),
    一年級女生=str_replace(一年級女生,",","")
  ) %>%
  mutate(
    一年級男生=as.numeric(一年級男生),
    一年級女生=as.numeric(一年級女生)
  ) -> collegeData3
```

```{r}
library(readr)
cl<-locale(grouping_mark = ",") # 創造cl來描述千分位符號使用","的習慣場景
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,locale=cl),
    一年級女生=parse_number(一年級女生,locale=cl)
  ) -> collegeData4
```

# 運用 parse_number 與 場景locale設定

```{r}
library(readr)
cl<-locale(grouping_mark = ",") # 創造cl來描述千分位符號使用","的習慣場景
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,na=c("","NA","-"),locale=cl),
    一年級女生=parse_number(一年級女生,na=c("","NA","-"),locale=cl)
  ) -> collegeData4
```

```{r}
problems(collegeData4$一年級男生)
collegeData$一年級男生[c(14,76,88)]
```

```{r}
collegeData %>% 
  mutate(
    `日間∕進修別`=as.factor(`日間∕進修別`),
    等級別=as.factor(等級別),
    一年級男生=parse_number(一年級男生,locale=cl),
    一年級女生=parse_number(一年級女生,locale=cl),
    一年級男生每千人=一年級男生/1000,
    一年級女生每千人=一年級女生/1000
    ) -> collegeData5
```

```{r}
collegeData %>%
  select(一年級男生,一年級女生,
              二年級男生, 二年級女生) -> college1stYearData
```

```{r}
college1stYearData %>%
  mutate(
    一年級男生=parse_number(一年級男生,locale=cl),
    一年級女生=parse_number(...),
    二年級男生=parse_number(...), 
    二年級女生=parse_number(...)
  )
```

parse_number(.,locale=cl)

```{r}
college1stYearData %>%
  mutate_all(
    funs(
      parse_number(.,locale=cl)
    )
  ) ->college1stYearDataNumeric
head(college1stYearDataNumeric)
```

```{r}
college1stYearDataNumeric %>%
  mutate_all(
    funs(
      每百人=./100,
      每千人=./1000
    )
  ) -> college1stYearDataNumeric
college1stYearDataNumeric %>% colnames
# old writing
colnames(college1stYearDataNumeric)
```

```{r}
collegeData %>% colnames
```

```{r}
collegeData %>%
  mutate_at(
    vars(
      contains("生")
    ),
    funs(
      parse_number(.,locale=cl,na=c("","NA","-"))
    )
  ) -> collegeData5
collegeData5 %>% str
```